"""The Artwork Studio — commercial asset production.

This is the missing production stage: it turns an approved **master design**
into the **actual image files** required to sell a product — not prompts, not
descriptions, not placeholders. For a design (and, per product, the approved
product set) it produces:

* ``master_artwork.png`` — the original commercial artwork.
* ``print_file.png`` — the print file for Gelato (correct size/resolution,
  transparent background where appropriate).
* product artwork — the artwork adapted for the specific product.
* mock-ups — real commercial scenes (hero, lifestyle, close-up, scale, room).
* a complete Etsy gallery of 8-10 conversion-focused images.

Every generated image passes a **deterministic quality gate** before it is
accepted (valid, correctly sized, not blank/flat, readable content); a failing
image is **regenerated** (a fresh composition) up to a bounded number of
attempts, keeping the best result. The quality gate is a measurable check, not
a new AI agent.

Image generation is delegated to a replaceable :class:`ImageBackend`
(:mod:`onassis.connectors.image_backend`). The Studio never talks to an image
provider directly, so ONASSIS is not locked to one. If the configured backend
fails on an image, the Studio falls back to the local renderer so a real file
is always produced.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from onassis.config import Config
from onassis.connectors.image_backend import (
    GALLERY, MASTER, MOCKUP, PRINT, PRODUCT, ImageBackend, ImageSpec,
    LocalRenderBackend, build_image_backend,
)
from onassis.logger import get_logger

log = get_logger(__name__)

# The commercial image plan for a product's Etsy gallery: an ordered set of
# mock-up scenes, padded with gallery variants to hit the configured target.
_SCENES = ["hero", "lifestyle", "closeup", "scale", "room"]


class ArtworkReview:
    """A deterministic quality gate for generated artwork (not an AI agent).

    It answers, with measurable proxies, whether an image is fit to sell:
    is it a valid image, correctly sized, not blank or flat (has real content),
    and does it carry visible, readable detail? Anything below the bar is
    regenerated by the Studio.
    """

    def __init__(self, cfg: dict[str, Any] | None = None) -> None:
        cfg = cfg or {}
        self.min_coverage = float(cfg.get("min_coverage", 0.015))
        self.max_coverage = float(cfg.get("max_coverage", 0.995))
        self.min_stddev = float(cfg.get("min_stddev", 6.0))
        self.min_bytes = int(cfg.get("min_bytes", 800))

    def evaluate(self, data: bytes, spec: ImageSpec) -> dict[str, Any]:
        import io

        from PIL import Image, ImageStat

        reasons: list[str] = []
        try:
            img = Image.open(io.BytesIO(data))
            img.load()
        except Exception as exc:  # not a valid image
            return {"accepted": False, "score": 0.0,
                    "reasons": [f"invalid image: {exc}"], "checks": {}}

        size_ok = abs(img.width - spec.width) <= 2 and abs(img.height - spec.height) <= 2
        bytes_ok = len(data) >= self.min_bytes

        # Content coverage: fraction of pixels that carry the design (ink), vs a
        # flat background. Transparent print files use the alpha channel.
        if spec.transparent and "A" in img.getbands():
            raw = img.getchannel("A").resize((96, 96)).tobytes()  # 1 byte/px, downsampled
            coverage = sum(1 for p in raw if p > 16) / max(1, len(raw))
        else:
            coverage = self._ink_coverage(img.convert("RGB"))
        coverage_ok = self.min_coverage <= coverage <= self.max_coverage

        # Visible detail / contrast (typography + composition readability).
        stddev = max(ImageStat.Stat(img.convert("L")).stddev or [0.0])
        detail_ok = stddev >= self.min_stddev

        if not size_ok:
            reasons.append(f"wrong size {img.size} (wanted {spec.width}x{spec.height})")
        if not bytes_ok:
            reasons.append("image too small / empty")
        if not coverage_ok:
            reasons.append(f"content coverage {coverage:.3f} out of range")
        if not detail_ok:
            reasons.append(f"too flat (stddev {stddev:.1f})")

        checks = {"size_ok": size_ok, "bytes_ok": bytes_ok,
                  "coverage": round(coverage, 4), "coverage_ok": coverage_ok,
                  "stddev": round(stddev, 2), "detail_ok": detail_ok}
        accepted = size_ok and bytes_ok and coverage_ok and detail_ok
        score = round(100.0 * (coverage_ok + detail_ok + size_ok + bytes_ok) / 4.0, 1)
        return {"accepted": accepted, "score": score, "reasons": reasons, "checks": checks}

    @staticmethod
    def _ink_coverage(rgb) -> float:
        """Fraction of pixels that differ noticeably from the background colour."""
        raw = rgb.resize((64, 64)).tobytes()  # 3 bytes/px (RGB), downsampled
        bg = (raw[0], raw[1], raw[2])         # background ≈ top-left corner
        n = len(raw) // 3
        diff = sum(1 for i in range(0, len(raw), 3)
                   if abs(raw[i] - bg[0]) + abs(raw[i + 1] - bg[1])
                   + abs(raw[i + 2] - bg[2]) > 40)
        return diff / max(1, n)


class ArtworkStudio:
    """Produces the real commercial image files for a design and its products."""

    def __init__(self, config: Config, db: Any | None = None,
                 backend: ImageBackend | None = None) -> None:
        self.config = config
        self.db = db
        self.cfg = getattr(config, "image", None) or {}
        self._backend = backend or build_image_backend(config)
        self._fallback = LocalRenderBackend()
        self.review = ArtworkReview(self.cfg.get("quality"))
        self.max_attempts = int(self.cfg.get("max_attempts", 3))
        self.master_px = int(self.cfg.get("master_px", 2048))
        self.print_px = int(self.cfg.get("print_px", 3600))  # ~300 DPI over A3-ish
        self.gallery_px = int(self.cfg.get("gallery_px", 1200))
        self.gallery_count = max(8, min(10, int(self.cfg.get("gallery_count", 9))))

    @property
    def backend_name(self) -> str:
        return self._backend.name

    # --- Generation with the quality gate ---------------------------

    def _produce(self, spec: ImageSpec) -> tuple[bytes, dict[str, Any]]:
        """Generate one image, regenerating on QC failure; return the best."""
        best: tuple[bytes, dict[str, Any]] | None = None
        for attempt in range(1, self.max_attempts + 1):
            spec.variant = attempt - 1
            data = self._generate(spec)
            verdict = self.review.evaluate(data, spec)
            verdict["attempts"] = attempt
            if verdict["accepted"]:
                return data, verdict
            if best is None or verdict["score"] > best[1]["score"]:
                best = (data, verdict)
            log.info("Artwork QC rejected %s/%s (attempt %d): %s — regenerating.",
                     spec.kind, spec.scene, attempt, "; ".join(verdict["reasons"]))
        assert best is not None
        log.warning("Artwork QC accepted best-effort %s/%s after %d attempts (score %.0f).",
                    best[1].get("kind", spec.kind), spec.scene, self.max_attempts,
                    best[1]["score"])
        return best

    def _generate(self, spec: ImageSpec) -> bytes:
        try:
            return self._backend.generate(spec)
        except Exception as exc:  # replaceable backend failed — never lose the file
            log.warning("Image backend '%s' failed (%s); falling back to local renderer.",
                        self._backend.name, exc)
            return self._fallback.generate(spec)

    # --- Master design assets ---------------------------------------

    def generate_master(self, design_package: dict[str, Any], out_dir: Path) -> dict[str, Any]:
        """Produce ``master_artwork.png`` + ``print_file.png`` for a design."""
        out_dir = Path(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        brief = design_package.get("design_brief", design_package)
        spec_common = self._design_context(brief)

        master_spec = ImageSpec(kind=MASTER, width=self.master_px, height=self.master_px,
                                transparent=False, prompt=self._prompt(brief, "master artwork"),
                                **spec_common)
        master_bytes, master_qc = self._produce(master_spec)
        (out_dir / "master_artwork.png").write_bytes(master_bytes)

        transparent = bool(brief.get("transparent_background_required", True))
        print_spec = ImageSpec(kind=PRINT, width=self.print_px, height=self.print_px,
                               transparent=transparent,
                               prompt=self._prompt(brief, "print file, transparent background"),
                               **spec_common)
        print_bytes, print_qc = self._produce(print_spec)
        (out_dir / "print_file.png").write_bytes(print_bytes)

        log.info("Master artwork ready at %s (backend=%s).", out_dir, self.backend_name)
        return {
            "status": "ready",
            "backend": self.backend_name,
            "path": str(out_dir),
            "files": ["master_artwork.png", "print_file.png"],
            "master_review": master_qc,
            "print_review": print_qc,
            "dpi": int(brief.get("dpi_requirement", 300)),
        }

    # --- Per-product commercial gallery -----------------------------

    def build_product_gallery(
        self, design_package: dict[str, Any], product: dict[str, Any],
        images_dir: Path, *, alt_texts: list[str] | None = None,
    ) -> list[dict[str, Any]]:
        """Produce the ordered commercial gallery for one product as real files.

        Writes into ``images_dir`` and returns an ordered image manifest —
        ``[{order, filename, kind, scene, alt_text, review}]`` — that the Listing
        Factory embeds and the Publisher uploads. 8-10 images, conversion-first.
        """
        images_dir = Path(images_dir)
        images_dir.mkdir(parents=True, exist_ok=True)
        brief = design_package.get("design_brief", design_package)
        ctx = self._design_context(brief)
        product_type = product.get("product_name") or product.get("product_key") or ""
        product_key = product.get("product_key") or "product"

        plan = self._gallery_plan()
        manifest: list[dict[str, Any]] = []
        for order, (filename, kind, scene) in enumerate(plan, start=1):
            spec = ImageSpec(
                kind=kind, width=self.gallery_px, height=self.gallery_px,
                product_type=product_type, product_key=product_key, scene=scene,
                prompt=self._prompt(brief, f"{scene} image of a {product_type}"),
                **ctx,
            )
            data, qc = self._produce(spec)
            (images_dir / filename).write_bytes(data)
            alt = (alt_texts[order - 1] if alt_texts and order - 1 < len(alt_texts)
                   else self._alt(brief, product_type, scene))
            manifest.append({"order": order, "filename": filename, "kind": kind,
                             "scene": scene, "alt_text": alt, "review": qc,
                             "source": self.backend_name})
        log.info("Built %d commercial image(s) for %s at %s.",
                 len(manifest), product_key, images_dir)
        return manifest

    def _gallery_plan(self) -> list[tuple[str, str, str]]:
        """(filename, kind, scene) for the ordered commercial gallery."""
        plan: list[tuple[str, str, str]] = [("hero.jpg", MOCKUP, "hero")]
        mock_scenes = ["lifestyle", "closeup", "scale"]
        for i, scene in enumerate(mock_scenes, start=1):
            plan.append((f"mockup_{i:02d}.jpg", MOCKUP, scene))
        # Gallery variants (room scene, product-front, extra scenes) to hit target.
        remaining = self.gallery_count - len(plan)
        gallery_scenes = ["room", "product", "hero", "lifestyle", "closeup", "room"]
        for i in range(1, remaining + 1):
            scene = gallery_scenes[(i - 1) % len(gallery_scenes)]
            kind = PRODUCT if scene == "product" else GALLERY
            plan.append((f"gallery_{i:02d}.jpg", kind, "hero" if scene == "product" else scene))
        return plan

    # --- Design context / prompts -----------------------------------

    def _design_context(self, brief: dict[str, Any]) -> dict[str, Any]:
        palette = self._palette(brief)
        return {
            "palette": palette,
            "title": brief.get("listing_title_seed") or brief.get("product_name") or "",
            "subtitle": brief.get("brand") or (self.config.brand or {}).get("name", ""),
            "motif": brief.get("theme", "coastal"),
        }

    def _palette(self, brief: dict[str, Any]) -> list[str]:
        colours = [brief.get("shirt_colour"), brief.get("print_colour"),
                   brief.get("primary_colour"), brief.get("secondary_colour")]
        colours = [c for c in colours if c]
        return colours or ["ecru", "terracotta", "sea", "olive"]

    def _prompt(self, brief: dict[str, Any], subject: str) -> str:
        return (
            f"Premium Mediterranean lifestyle {subject} for '{brief.get('product_name', '')}'. "
            f"{brief.get('artwork_description', '')} "
            f"Palette: {', '.join(self._palette(brief))}. "
            f"Typography: {brief.get('typography_direction', 'elegant serif')}. "
            f"Editorial, natural light, high-end, conversion-focused. "
            f"Original work only — no trademarks or copyrighted characters."
        )

    def _alt(self, brief: dict[str, Any], product_type: str, scene: str) -> str:
        name = brief.get("product_name") or product_type
        label = {"hero": "hero image", "lifestyle": "lifestyle scene",
                 "closeup": "close-up of the artwork", "scale": "scale reference",
                 "room": "styled room scene"}.get(scene, scene)
        return f"{name} on a {product_type} — {label}"[:250]
